/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

/**
 *
 * @author szoplakz
 */
public class AuthorSearchForm extends javax.swing.JFrame {

    /**
     * Creates new form AuthorSearchForm
     */
    public AuthorSearchForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AuthorSearchIcon = new javax.swing.JLabel();
        AuthorNameLabel = new javax.swing.JLabel();
        AuthorNameSearchTextField = new javax.swing.JTextField();
        AuthorBooksLabel = new javax.swing.JLabel();
        AuthorBookSearchTextField = new javax.swing.JTextField();
        BrithAuthorSearchLabel = new javax.swing.JLabel();
        BrirthAuthorSearchMinimumTextField = new javax.swing.JTextField();
        BirthAuthorSeparatorLabel = new javax.swing.JLabel();
        BrithAuthorSearchMaxiimumTextField = new javax.swing.JTextField();
        DeathAuthorSearchLabel = new javax.swing.JLabel();
        BrirthAuthorSearchMinimumTextField1 = new javax.swing.JTextField();
        BirthAuthorSeparatorLabel1 = new javax.swing.JLabel();
        BrithAuthorSearchMaxiimumTextField1 = new javax.swing.JTextField();
        LifeStatusSearchLabel = new javax.swing.JLabel();
        LifeStatusSerachComboBox = new javax.swing.JComboBox<>();
        GenreSearchLabel = new javax.swing.JLabel();
        GenreSerachComboBox = new javax.swing.JComboBox<>();
        NationalitySearchLabel = new javax.swing.JLabel();
        NationalitySerachComboBox = new javax.swing.JComboBox<>();
        GenderSearchLabel = new javax.swing.JLabel();
        GenderSerachComboBox = new javax.swing.JComboBox<>();
        AuthorSearchFilterButton = new javax.swing.JButton();
        AuthorSearchViewButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AuhorListList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AuthorSearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/navrhy/AuthorSearchIcon.png"))); // NOI18N

        AuthorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AuthorNameLabel.setForeground(new java.awt.Color(0, 102, 204));
        AuthorNameLabel.setText("Name:");

        AuthorBooksLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AuthorBooksLabel.setForeground(new java.awt.Color(0, 102, 204));
        AuthorBooksLabel.setText("By Book Name:");

        BrithAuthorSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BrithAuthorSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        BrithAuthorSearchLabel.setText("Year of Birth");

        BrirthAuthorSearchMinimumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrirthAuthorSearchMinimumTextFieldActionPerformed(evt);
            }
        });

        BirthAuthorSeparatorLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BirthAuthorSeparatorLabel.setForeground(new java.awt.Color(0, 102, 255));
        BirthAuthorSeparatorLabel.setText("to");

        DeathAuthorSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeathAuthorSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        DeathAuthorSearchLabel.setText("Year of Death");

        BrirthAuthorSearchMinimumTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrirthAuthorSearchMinimumTextField1ActionPerformed(evt);
            }
        });

        BirthAuthorSeparatorLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BirthAuthorSeparatorLabel1.setForeground(new java.awt.Color(0, 102, 255));
        BirthAuthorSeparatorLabel1.setText("to");

        LifeStatusSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LifeStatusSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        LifeStatusSearchLabel.setText("Life Status:");

        LifeStatusSerachComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Both", "Alive", "Dead", " " }));

        GenreSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenreSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        GenreSearchLabel.setText("By Genre:");

        NationalitySearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NationalitySearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        NationalitySearchLabel.setText("Nationality:");

        GenderSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenderSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        GenderSearchLabel.setText("Gender:");

        GenderSerachComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Both", "Male", "Female", " " }));

        AuthorSearchFilterButton.setText("Filter");
        AuthorSearchFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorSearchFilterButtonActionPerformed(evt);
            }
        });

        AuthorSearchViewButton.setText("View");

        AuhorListList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(AuhorListList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AuthorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AuthorNameSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AuthorBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AuthorBookSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(AuthorSearchIcon))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeathAuthorSearchLabel)
                            .addComponent(BrithAuthorSearchLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BrirthAuthorSearchMinimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthAuthorSeparatorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BrithAuthorSearchMaxiimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(GenderSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderSerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BrirthAuthorSearchMinimumTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthAuthorSeparatorLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BrithAuthorSearchMaxiimumTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AuthorSearchFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AuthorSearchViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LifeStatusSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LifeStatusSerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenreSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenreSerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NationalitySearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NationalitySerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AuthorNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AuthorNameSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AuthorBooksLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AuthorBookSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AuthorSearchIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GenreSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenreSerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NationalitySearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NationalitySerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LifeStatusSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LifeStatusSerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenderSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenderSerachComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(BrithAuthorSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BrirthAuthorSearchMinimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BirthAuthorSeparatorLabel)
                            .addComponent(BrithAuthorSearchMaxiimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(DeathAuthorSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BrirthAuthorSearchMinimumTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BirthAuthorSeparatorLabel1)
                            .addComponent(BrithAuthorSearchMaxiimumTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AuthorSearchFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AuthorSearchViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BrirthAuthorSearchMinimumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrirthAuthorSearchMinimumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrirthAuthorSearchMinimumTextFieldActionPerformed

    private void BrirthAuthorSearchMinimumTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrirthAuthorSearchMinimumTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrirthAuthorSearchMinimumTextField1ActionPerformed

    private void AuthorSearchFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorSearchFilterButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AuthorSearchFilterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthorSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthorSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthorSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthorSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthorSearchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AuhorListList;
    private javax.swing.JTextField AuthorBookSearchTextField;
    private javax.swing.JLabel AuthorBooksLabel;
    private javax.swing.JLabel AuthorNameLabel;
    private javax.swing.JTextField AuthorNameSearchTextField;
    private javax.swing.JButton AuthorSearchFilterButton;
    private javax.swing.JLabel AuthorSearchIcon;
    private javax.swing.JButton AuthorSearchViewButton;
    private javax.swing.JLabel BirthAuthorSeparatorLabel;
    private javax.swing.JLabel BirthAuthorSeparatorLabel1;
    private javax.swing.JTextField BrirthAuthorSearchMinimumTextField;
    private javax.swing.JTextField BrirthAuthorSearchMinimumTextField1;
    private javax.swing.JLabel BrithAuthorSearchLabel;
    private javax.swing.JTextField BrithAuthorSearchMaxiimumTextField;
    private javax.swing.JTextField BrithAuthorSearchMaxiimumTextField1;
    private javax.swing.JLabel DeathAuthorSearchLabel;
    private javax.swing.JLabel GenderSearchLabel;
    private javax.swing.JComboBox<String> GenderSerachComboBox;
    private javax.swing.JLabel GenreSearchLabel;
    private javax.swing.JComboBox<String> GenreSerachComboBox;
    private javax.swing.JLabel LifeStatusSearchLabel;
    private javax.swing.JComboBox<String> LifeStatusSerachComboBox;
    private javax.swing.JLabel NationalitySearchLabel;
    private javax.swing.JComboBox<String> NationalitySerachComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
