/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

/**
 *
 * @author szoplakz
 */
public class BookSearchForm extends javax.swing.JFrame {

    /**
     * Creates new form SearchForm
     */
    public BookSearchForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        VirtualLibraryIntroLabel = new javax.swing.JLabel();
        BookSearchIconLabel = new javax.swing.JLabel();
        BookNameLabel = new javax.swing.JLabel();
        BookNameSearchTextField = new javax.swing.JTextField();
        AuthorNameLabel = new javax.swing.JLabel();
        AuthorNameSearchTextField = new javax.swing.JTextField();
        YearBookSearchLabel = new javax.swing.JLabel();
        YearBookSearchMinimumTextField = new javax.swing.JTextField();
        YearSearchSeparatorLabel = new javax.swing.JLabel();
        YearBookSearchMaxiimumTextField = new javax.swing.JTextField();
        TagBookSearchLabel = new javax.swing.JLabel();
        ISBMBookSearchTextField = new javax.swing.JTextField();
        NumberOfPagesBookSearchLabel = new javax.swing.JLabel();
        NumberofPagesBookSearchMaximumTextField = new javax.swing.JTextField();
        RatingsBookSearchMaximumTextField = new javax.swing.JTextField();
        NumberofPagesSearchSeparatorLabel = new javax.swing.JLabel();
        GenreBookSearchLabel = new javax.swing.JLabel();
        GenreSelectorComboBox = new javax.swing.JComboBox<>();
        ISBNBookSearchLabel1 = new javax.swing.JLabel();
        TagBookSearchTextField = new javax.swing.JTextField();
        RatingsBookSearchLabel = new javax.swing.JLabel();
        NumberofPagesBookSearchMinimumTextField2 = new javax.swing.JTextField();
        RatingBookSearchMinimumTextField = new javax.swing.JTextField();
        RatingsSearchSeparatorLabel = new javax.swing.JLabel();
        BookSearchFilterButton = new javax.swing.JButton();
        BookSearchViewButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BookListList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VirtualLibraryIntroLabel.setFont(new java.awt.Font("Lucida Handwriting", 3, 14)); // NOI18N
        VirtualLibraryIntroLabel.setForeground(new java.awt.Color(0, 102, 204));
        VirtualLibraryIntroLabel.setText("Welcome to our Virtual Library !");

        BookSearchIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/navrhy/SearchBookIcon.png"))); // NOI18N

        BookNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BookNameLabel.setForeground(new java.awt.Color(0, 102, 204));
        BookNameLabel.setText("Name:");

        AuthorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AuthorNameLabel.setForeground(new java.awt.Color(0, 102, 255));
        AuthorNameLabel.setText("Author:");

        YearBookSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        YearBookSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        YearBookSearchLabel.setText("Year of publication:");

        YearBookSearchMinimumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearBookSearchMinimumTextFieldActionPerformed(evt);
            }
        });

        YearSearchSeparatorLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        YearSearchSeparatorLabel.setForeground(new java.awt.Color(0, 102, 255));
        YearSearchSeparatorLabel.setText("to");

        TagBookSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TagBookSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        TagBookSearchLabel.setText("Tags:");

        NumberOfPagesBookSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NumberOfPagesBookSearchLabel.setForeground(new java.awt.Color(0, 102, 255));
        NumberOfPagesBookSearchLabel.setText("Length:");

        RatingsBookSearchMaximumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingsBookSearchMaximumTextFieldActionPerformed(evt);
            }
        });

        NumberofPagesSearchSeparatorLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NumberofPagesSearchSeparatorLabel.setForeground(new java.awt.Color(0, 102, 255));
        NumberofPagesSearchSeparatorLabel.setText("to");

        GenreBookSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenreBookSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        GenreBookSearchLabel.setText("Genre:");

        GenreSelectorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GenreSelectorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenreSelectorComboBoxActionPerformed(evt);
            }
        });

        ISBNBookSearchLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ISBNBookSearchLabel1.setForeground(new java.awt.Color(0, 102, 204));
        ISBNBookSearchLabel1.setText("ISBN:");

        RatingsBookSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RatingsBookSearchLabel.setForeground(new java.awt.Color(0, 102, 255));
        RatingsBookSearchLabel.setText("Rating:");

        NumberofPagesBookSearchMinimumTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberofPagesBookSearchMinimumTextField2ActionPerformed(evt);
            }
        });

        RatingBookSearchMinimumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RatingBookSearchMinimumTextFieldActionPerformed(evt);
            }
        });

        RatingsSearchSeparatorLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RatingsSearchSeparatorLabel.setForeground(new java.awt.Color(0, 102, 255));
        RatingsSearchSeparatorLabel.setText("to");

        BookSearchFilterButton.setText("Filter");

        BookSearchViewButton.setText("View");

        BookListList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(BookListList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AuthorNameLabel)
                                .addGap(202, 202, 202)
                                .addComponent(GenreBookSearchLabel))
                            .addComponent(VirtualLibraryIntroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookNameSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookSearchIconLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(AuthorNameSearchTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addComponent(ISBMBookSearchTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(ISBNBookSearchLabel1)
                            .addComponent(YearBookSearchLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YearBookSearchMinimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YearSearchSeparatorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(YearBookSearchMaxiimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NumberOfPagesBookSearchLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NumberofPagesBookSearchMinimumTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberofPagesSearchSeparatorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberofPagesBookSearchMaximumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BookSearchFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BookSearchViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RatingBookSearchMinimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RatingsSearchSeparatorLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RatingsBookSearchMaximumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TagBookSearchLabel)
                                    .addComponent(TagBookSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GenreSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RatingsBookSearchLabel))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VirtualLibraryIntroLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BookNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BookNameSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AuthorNameLabel)
                            .addComponent(GenreBookSearchLabel)))
                    .addComponent(BookSearchIconLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AuthorNameSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenreSelectorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISBNBookSearchLabel1)
                    .addComponent(TagBookSearchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISBMBookSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TagBookSearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(YearBookSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YearBookSearchMinimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YearSearchSeparatorLabel)
                            .addComponent(YearBookSearchMaxiimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumberOfPagesBookSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NumberofPagesBookSearchMinimumTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumberofPagesSearchSeparatorLabel)
                            .addComponent(NumberofPagesBookSearchMaximumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RatingsBookSearchLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RatingBookSearchMinimumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RatingsSearchSeparatorLabel)
                            .addComponent(RatingsBookSearchMaximumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookSearchViewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookSearchFilterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void YearBookSearchMinimumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearBookSearchMinimumTextFieldActionPerformed
       // by sme mohli dajake Buttony pomaly naimplementovať
    }//GEN-LAST:event_YearBookSearchMinimumTextFieldActionPerformed

    private void RatingsBookSearchMaximumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingsBookSearchMaximumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RatingsBookSearchMaximumTextFieldActionPerformed

    private void GenreSelectorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenreSelectorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenreSelectorComboBoxActionPerformed

    private void NumberofPagesBookSearchMinimumTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberofPagesBookSearchMinimumTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberofPagesBookSearchMinimumTextField2ActionPerformed

    private void RatingBookSearchMinimumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RatingBookSearchMinimumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RatingBookSearchMinimumTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSearchForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSearchForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthorNameLabel;
    private javax.swing.JTextField AuthorNameSearchTextField;
    private javax.swing.JList<String> BookListList;
    private javax.swing.JLabel BookNameLabel;
    private javax.swing.JTextField BookNameSearchTextField;
    private javax.swing.JButton BookSearchFilterButton;
    private javax.swing.JLabel BookSearchIconLabel;
    private javax.swing.JButton BookSearchViewButton;
    private javax.swing.JLabel GenreBookSearchLabel;
    private javax.swing.JComboBox<String> GenreSelectorComboBox;
    private javax.swing.JTextField ISBMBookSearchTextField;
    private javax.swing.JLabel ISBNBookSearchLabel1;
    private javax.swing.JLabel NumberOfPagesBookSearchLabel;
    private javax.swing.JTextField NumberofPagesBookSearchMaximumTextField;
    private javax.swing.JTextField NumberofPagesBookSearchMinimumTextField2;
    private javax.swing.JLabel NumberofPagesSearchSeparatorLabel;
    private javax.swing.JTextField RatingBookSearchMinimumTextField;
    private javax.swing.JLabel RatingsBookSearchLabel;
    private javax.swing.JTextField RatingsBookSearchMaximumTextField;
    private javax.swing.JLabel RatingsSearchSeparatorLabel;
    private javax.swing.JLabel TagBookSearchLabel;
    private javax.swing.JTextField TagBookSearchTextField;
    private javax.swing.JLabel VirtualLibraryIntroLabel;
    private javax.swing.JLabel YearBookSearchLabel;
    private javax.swing.JTextField YearBookSearchMaxiimumTextField;
    private javax.swing.JTextField YearBookSearchMinimumTextField;
    private javax.swing.JLabel YearSearchSeparatorLabel;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
