/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

/**
 *
 * @author szoplakz
 */
public class MyAdminProfileForm extends javax.swing.JFrame {

    /**
     * Creates new form UserProfileForm
     */
    public MyAdminProfileForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserProfileUserNameLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        UserProfileUserNameLabel = new javax.swing.JLabel();
        BookIconLabel = new javax.swing.JLabel();
        UserProfileEmailLabel = new javax.swing.JLabel();
        UserProfileFullNameLabel = new javax.swing.JLabel();
        UserProfileStatusLabel = new javax.swing.JLabel();
        FavoriteBooksLabel = new javax.swing.JLabel();
        FavouriteBookIconButton = new javax.swing.JButton();
        ReadBooksLabel = new javax.swing.JLabel();
        ReadBooksIconButton = new javax.swing.JButton();
        WantedBooksIconButton = new javax.swing.JButton();
        FavouriteAuthorsLabel = new javax.swing.JLabel();
        FavouriteAuthorsIconButton = new javax.swing.JButton();
        FriendsLabel = new javax.swing.JLabel();
        FriendsIconButton = new javax.swing.JButton();
        FavouriteReviewersLabel = new javax.swing.JLabel();
        FavouriteReviewersIconButton = new javax.swing.JButton();
        MyReviewsLabel = new javax.swing.JLabel();
        BookReviewsIconButton = new javax.swing.JButton();
        BookReviewsLabel = new javax.swing.JLabel();
        AuthorReviewsLabel = new javax.swing.JLabel();
        AuthorReviewIconButton = new javax.swing.JButton();
        SearchIconButton = new javax.swing.JButton();
        WantedBooksLabel = new javax.swing.JLabel();
        SearchLabelLine1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ManageProfileButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        DeleteProfileButton = new javax.swing.JButton();
        InspectRequests = new javax.swing.JLabel();
        InspectRequestsButton = new javax.swing.JButton();
        DeleteUsersLabel = new javax.swing.JLabel();
        DeleteUserButton = new javax.swing.JButton();
        SearchSubjectSelector = new javax.swing.JComboBox<>();

        UserProfileUserNameLabel1.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        UserProfileUserNameLabel1.setForeground(new java.awt.Color(0, 0, 102));
        UserProfileUserNameLabel1.setText("Welcome (UserNameHere) !");

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserProfileUserNameLabel.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        UserProfileUserNameLabel.setForeground(new java.awt.Color(0, 0, 102));
        UserProfileUserNameLabel.setText("Welcome (UserNameHere) !");

        BookIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/kniha4.png"))); // NOI18N

        UserProfileEmailLabel.setText("E-mail: (EmailHere)");

        UserProfileFullNameLabel.setText("Full Name: (NameSurnameHere)");

        UserProfileStatusLabel.setText("Status: (User or Admin)");

        FavoriteBooksLabel.setText(" Favourite Books:");

        FavouriteBookIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteIcon.png"))); // NOI18N

        ReadBooksLabel.setText("Read Books:");

        ReadBooksIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/TickIcon.png"))); // NOI18N

        WantedBooksIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/WantedBookIcon.png"))); // NOI18N

        FavouriteAuthorsLabel.setText("Favourite Authors:");

        FavouriteAuthorsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteAuthorsIcon.png"))); // NOI18N

        FriendsLabel.setText("Friends:");

        FriendsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FriendsIcon.png"))); // NOI18N
        FriendsIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendsIconButtonActionPerformed(evt);
            }
        });

        FavouriteReviewersLabel.setText("Favourite Reviewers:");

        FavouriteReviewersIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteReviewersIcon.png"))); // NOI18N

        MyReviewsLabel.setText("My Reviews:");

        BookReviewsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/BookReviewsIcon.png"))); // NOI18N

        BookReviewsLabel.setText("Books:");

        AuthorReviewsLabel.setText("Authors:");

        AuthorReviewIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/AuthorReviewIcon.png"))); // NOI18N

        SearchIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/SearchIcon.png"))); // NOI18N
        SearchIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIconButtonActionPerformed(evt);
            }
        });

        WantedBooksLabel.setText("Wanted Books:");

        SearchLabelLine1.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        SearchLabelLine1.setForeground(new java.awt.Color(0, 0, 102));
        SearchLabelLine1.setText("Search for your favourite books, authors");

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("and users here !");

        ManageProfileButton.setText("Manage Profile");

        LogoutButton.setText("Logout");

        DeleteProfileButton.setText("Delete Profile");

        InspectRequests.setText("Inspect Requests:");

        InspectRequestsButton.setIcon(new javax.swing.ImageIcon("C:\\projektobrazky\\InspectRequestsIcon.png")); // NOI18N

        DeleteUsersLabel.setText("Delete Users:");

        DeleteUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/DeleteUserIcon.png"))); // NOI18N

        SearchSubjectSelector.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        SearchSubjectSelector.setForeground(new java.awt.Color(0, 102, 204));
        SearchSubjectSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Books", "Authors", "Reviews" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserProfileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserProfileStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BookReviewsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyReviewsLabel)
                            .addComponent(BookReviewsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserProfileFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AuthorReviewIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SearchIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SearchLabelLine1)
                            .addComponent(jLabel2)
                            .addComponent(SearchSubjectSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookIconLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManageProfileButton)
                            .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AuthorReviewsLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(UserProfileUserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InspectRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InspectRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteUsersLabel)
                            .addComponent(DeleteUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FavouriteBookIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ReadBooksLabel)
                                    .addComponent(ReadBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FavouriteAuthorsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FriendsLabel)
                                    .addComponent(FriendsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(FavouriteAuthorsLabel)
                            .addComponent(FavoriteBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FavouriteReviewersLabel)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FavouriteReviewersIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WantedBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WantedBooksLabel))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserProfileUserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UserProfileFullNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserProfileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserProfileStatusLabel)
                                .addGap(18, 18, 18)
                                .addComponent(MyReviewsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BookReviewsLabel)
                                .addGap(11, 11, 11)
                                .addComponent(BookReviewsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AuthorReviewsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AuthorReviewIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SearchIconButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ManageProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchSubjectSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SearchLabelLine1)
                                    .addComponent(DeleteProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FavoriteBooksLabel)
                                .addComponent(InspectRequests))
                            .addComponent(ReadBooksLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ReadBooksIconButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FavouriteBookIconButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InspectRequestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BookIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WantedBooksLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WantedBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FriendsLabel)
                    .addComponent(FavouriteAuthorsLabel)
                    .addComponent(FavouriteReviewersLabel)
                    .addComponent(DeleteUsersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(FavouriteReviewersIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5))
                        .addComponent(DeleteUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(FriendsIconButton)
                    .addComponent(FavouriteAuthorsIconButton))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIconButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchIconButtonActionPerformed

    private void FriendsIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendsIconButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FriendsIconButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAdminProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAdminProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAdminProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAdminProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAdminProfileForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AuthorReviewIconButton;
    private javax.swing.JLabel AuthorReviewsLabel;
    private javax.swing.JLabel BookIconLabel;
    private javax.swing.JButton BookReviewsIconButton;
    private javax.swing.JLabel BookReviewsLabel;
    private javax.swing.JButton DeleteProfileButton;
    private javax.swing.JButton DeleteUserButton;
    private javax.swing.JLabel DeleteUsersLabel;
    private javax.swing.JLabel FavoriteBooksLabel;
    private javax.swing.JButton FavouriteAuthorsIconButton;
    private javax.swing.JLabel FavouriteAuthorsLabel;
    private javax.swing.JButton FavouriteBookIconButton;
    private javax.swing.JButton FavouriteReviewersIconButton;
    private javax.swing.JLabel FavouriteReviewersLabel;
    private javax.swing.JButton FriendsIconButton;
    private javax.swing.JLabel FriendsLabel;
    private javax.swing.JLabel InspectRequests;
    private javax.swing.JButton InspectRequestsButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ManageProfileButton;
    private javax.swing.JLabel MyReviewsLabel;
    private javax.swing.JButton ReadBooksIconButton;
    private javax.swing.JLabel ReadBooksLabel;
    private javax.swing.JButton SearchIconButton;
    private javax.swing.JLabel SearchLabelLine1;
    private javax.swing.JComboBox<String> SearchSubjectSelector;
    private javax.swing.JLabel UserProfileEmailLabel;
    private javax.swing.JLabel UserProfileFullNameLabel;
    private javax.swing.JLabel UserProfileStatusLabel;
    private javax.swing.JLabel UserProfileUserNameLabel;
    private javax.swing.JLabel UserProfileUserNameLabel1;
    private javax.swing.JButton WantedBooksIconButton;
    private javax.swing.JLabel WantedBooksLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
