/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

/**
 *
 * @author szoplakz
 */
public class UserProfileForm extends javax.swing.JFrame {

    /**
     * Creates new form UserProfileForm
     */
    public UserProfileForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserProfileUserNameLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        UserProfileUserNameLabel = new javax.swing.JLabel();
        BookIconLabel = new javax.swing.JLabel();
        UserProfileEmailLabel = new javax.swing.JLabel();
        UserProfileFullNameLabel = new javax.swing.JLabel();
        UserProfileStatusLabel = new javax.swing.JLabel();
        FavoriteBooksLabel = new javax.swing.JLabel();
        FavouriteBookIconButton = new javax.swing.JButton();
        ReadBooksLabel = new javax.swing.JLabel();
        ReadBooksIconButton = new javax.swing.JButton();
        WantedBooksIconButton = new javax.swing.JButton();
        FavouriteAuthorsLabel = new javax.swing.JLabel();
        FavouriteAuthorsIconButton = new javax.swing.JButton();
        FriendsLabel = new javax.swing.JLabel();
        FriendsIconButton = new javax.swing.JButton();
        FavouriteReviewersLabel = new javax.swing.JLabel();
        FavouriteReviewersIconButton = new javax.swing.JButton();
        MyReviewsLabel = new javax.swing.JLabel();
        BookReviewsIconButton = new javax.swing.JButton();
        BookReviewsLabel = new javax.swing.JLabel();
        AuthorReviewsLabel = new javax.swing.JLabel();
        AuthorReviewIconButton = new javax.swing.JButton();
        WantedBooksLabel = new javax.swing.JLabel();
        AddFriendLabel = new javax.swing.JLabel();
        AddFriendsButton = new javax.swing.JButton();
        AddFavouriteReviewer = new javax.swing.JLabel();
        AddFavouriteReviewerButton = new javax.swing.JButton();

        UserProfileUserNameLabel1.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        UserProfileUserNameLabel1.setForeground(new java.awt.Color(0, 0, 102));
        UserProfileUserNameLabel1.setText("Welcome (UserNameHere) !");

        jButton2.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserProfileUserNameLabel.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        UserProfileUserNameLabel.setForeground(new java.awt.Color(0, 0, 102));
        UserProfileUserNameLabel.setText("(Username)'s profile");

        BookIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/kniha4.png"))); // NOI18N

        UserProfileEmailLabel.setText("E-mail: (EmailHere)");

        UserProfileFullNameLabel.setText("Full Name: (NameSurnameHere)");

        UserProfileStatusLabel.setText("Status: (User or Admin)");

        FavoriteBooksLabel.setText(" Favourite Books:");

        FavouriteBookIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteIcon.png"))); // NOI18N

        ReadBooksLabel.setText("Read Books:");

        ReadBooksIconButton.setIcon(new javax.swing.ImageIcon("C:\\projektobrazky\\TickIcon.png")); // NOI18N

        WantedBooksIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/WantedBookIcon.png"))); // NOI18N

        FavouriteAuthorsLabel.setText("Favourite Authors:");

        FavouriteAuthorsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteAuthorsIcon.png"))); // NOI18N

        FriendsLabel.setText("Friends:");

        FriendsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FriendsIcon.png"))); // NOI18N
        FriendsIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendsIconButtonActionPerformed(evt);
            }
        });

        FavouriteReviewersLabel.setText("Favourite Reviewers:");

        FavouriteReviewersIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteReviewersIcon.png"))); // NOI18N

        MyReviewsLabel.setText("(Username's) Reviews:");

        BookReviewsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/BookReviewsIcon.png"))); // NOI18N

        BookReviewsLabel.setText("Books:");

        AuthorReviewsLabel.setText("Authors:");

        AuthorReviewIconButton.setIcon(new javax.swing.ImageIcon("C:\\projektobrazky\\AuthorReviewIcon.png")); // NOI18N

        WantedBooksLabel.setText("Wanted Books:");

        AddFriendLabel.setText("Add to friends: ");

        AddFriendsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/AddFriendIcon.png"))); // NOI18N
        AddFriendsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFriendsButtonActionPerformed(evt);
            }
        });

        AddFavouriteReviewer.setText("Mark as favourite reviewer:");

        AddFavouriteReviewerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/AddFavouriteReviewerIcon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookReviewsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BookReviewsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MyReviewsLabel)
                            .addComponent(AuthorReviewIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FavoriteBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addComponent(FavouriteBookIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FavouriteAuthorsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FavouriteAuthorsLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddFavouriteReviewer)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReadBooksLabel)
                                .addGap(68, 68, 68)
                                .addComponent(WantedBooksLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ReadBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(WantedBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FriendsLabel)
                                    .addComponent(FriendsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FavouriteReviewersLabel)
                                    .addComponent(FavouriteReviewersIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddFriendsButton)
                        .addGap(18, 18, 18)
                        .addComponent(AddFavouriteReviewerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddFriendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserProfileFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserProfileUserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BookIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserProfileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserProfileStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AuthorReviewsLabel))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UserProfileUserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(UserProfileEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(UserProfileStatusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MyReviewsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BookReviewsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BookReviewsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddFriendLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddFavouriteReviewer))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddFriendsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddFavouriteReviewerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(UserProfileFullNameLabel)
                        .addComponent(BookIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AuthorReviewsLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ReadBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WantedBooksLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FavoriteBooksLabel)
                                        .addComponent(ReadBooksLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FavouriteBookIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WantedBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(AuthorReviewIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FriendsLabel)
                    .addComponent(FavouriteReviewersLabel)
                    .addComponent(FavouriteAuthorsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FavouriteAuthorsIconButton)
                    .addComponent(FavouriteReviewersIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FriendsIconButton))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FriendsIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendsIconButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FriendsIconButtonActionPerformed

    private void AddFriendsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFriendsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddFriendsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfileForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfileForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddFavouriteReviewer;
    private javax.swing.JButton AddFavouriteReviewerButton;
    private javax.swing.JLabel AddFriendLabel;
    private javax.swing.JButton AddFriendsButton;
    private javax.swing.JButton AuthorReviewIconButton;
    private javax.swing.JLabel AuthorReviewsLabel;
    private javax.swing.JLabel BookIconLabel;
    private javax.swing.JButton BookReviewsIconButton;
    private javax.swing.JLabel BookReviewsLabel;
    private javax.swing.JLabel FavoriteBooksLabel;
    private javax.swing.JButton FavouriteAuthorsIconButton;
    private javax.swing.JLabel FavouriteAuthorsLabel;
    private javax.swing.JButton FavouriteBookIconButton;
    private javax.swing.JButton FavouriteReviewersIconButton;
    private javax.swing.JLabel FavouriteReviewersLabel;
    private javax.swing.JButton FriendsIconButton;
    private javax.swing.JLabel FriendsLabel;
    private javax.swing.JLabel MyReviewsLabel;
    private javax.swing.JButton ReadBooksIconButton;
    private javax.swing.JLabel ReadBooksLabel;
    private javax.swing.JLabel UserProfileEmailLabel;
    private javax.swing.JLabel UserProfileFullNameLabel;
    private javax.swing.JLabel UserProfileStatusLabel;
    private javax.swing.JLabel UserProfileUserNameLabel;
    private javax.swing.JLabel UserProfileUserNameLabel1;
    private javax.swing.JButton WantedBooksIconButton;
    private javax.swing.JLabel WantedBooksLabel;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
